---
language: cpp
compiler: gcc
cache: ccache
sudo: false
addons:
  apt:
    sources:
    - kubuntu-backports
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.9
    - libasound2-dev
    - libpulse-dev
env:
  global:
  - secure: SLJCjkjDsTMbCIV9Wecz5JATnhk0fuzlnLMeZdvvFDv+8NL8cXyutkU0VfyRSLf3HSD1Js79a6fRMROyVGWj/w/BRrjqGnZzsB6+ZeJNnadiVIF5Gh+w90We5ccvSp2G4DyYgwkNnkKlJK7zNEWGu/K+bHL1EOCA+EIVrFMyA44=
  - numjobs=4
  - USE_CCACHE=1
  - CCACHE_SLOPPINESS=pch_defines,time_macros
  - CCACHE_COMPRESS=1
  - CCACHE_MAXSIZE=100M
before_script:
- export TRAVIS_COMMIT=$TRAVIS_COMMIT~
- export COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- git clone --depth 1 https://github.com/urho3d/fastcomp-clang.git && export LLVM_CLANG_ROOT=$(pwd)/fastcomp-clang
- export PATH=$(whereis -b ccache |grep -o '\S*lib\S*'):$PATH
- export CXX=g++-4.9 CC=gcc-4.9
- for compiler in gcc g++; do ln -s $(which ccache) $HOME/$compiler-4.9; done && export
  PATH=$HOME:$PATH
- rake ci_setup_cache
script: rake ci_annotate
after_script:
- rake ci_teardown_cache
- rake ci_delete_mirror
notifications:
  email:
    on_success: never
    on_failure: change
    recipients:
    - weitjong@gmail.com
